name: Go SLSA3 Publish

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write
  id-token: write
  actions: read

jobs:
  # === Сборка через SLSA ===
  slsa-build:
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@main
    with:
      go-version: 1.22
      output-dir: dist

  # === Публикация через GoReleaser ===
  goreleaser:
    needs: slsa-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Publish with GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
