name: SLSA Go releaser

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SLSA Go builder
        uses: slsa-framework/slsa-github-generator/go@v2
        with:
          go-version: 1.22
          upload-assets: true   # автоматически прикрепит бинарники + provenance в GitHub Release
