name: Go Release Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build .exe
        run: go build -o firewall-reset.exe ./...

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: firewall-reset.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
